name: FOSSA
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version-file: go.mod
      - name: Add GOPATH to GITHUB_ENV
        run: echo "GOPATH=$(go env GOPATH)" >>"$GITHUB_ENV"
      - name: Add GOPATH to GITHUB_PATH
        run: echo "$GOPATH/bin" >>"$GITHUB_PATH"
      - name: Run FOSSA scan and upload build data
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
          fossa analyze
          fossa test
